name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
<<<<<<< HEAD
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"
=======
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
>>>>>>> refs/remotes/origin/main

dependencies:
  camera_avfoundation:
    # When depending on this package from a real application you should use:
    #   camera_avfoundation: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  camera_platform_interface: 
    git: https://github.com/kumsumit/camera_platform_interface.git
  flutter:
    sdk: flutter
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  quiver: ^3.0.0
  video_player: 
    git: https://github.com/kumsumit/video_player.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
