name: camera_avfoundation_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  camera_avfoundation:
    path: ../
  camera_platform_interface:
    git: https://github.com/kumsumit/camera_platform_interface.git
  flutter:
    sdk: flutter
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  video_player:
    git: https://github.com/kumsumit/video_player.git

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
