name: camera_avfoundation
publish_to: none
description: iOS implementation of the camera plugin.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_avfoundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.9.17+5

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

flutter:
  plugin:
    implements: camera
    platforms:
      ios:
        pluginClass: CameraPlugin
        dartPluginClass: AVFoundationCamera

dependencies:
  camera_platform_interface:
    git: https://github.com/kumsumit/camera_platform_interface.git
  flutter:
    sdk: flutter
  stream_transform: ^2.1.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^22.4.2

topics:
  - camera
